### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by tischi** [saalfeldlab/hot-knife#5]
@axtimwalde Could you help me with that?

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hot-knife: Could not resolve dependencies for project saalfeldlab:hot-knife:jar:0.0.4-SNAPSHOT: Could not find artifact de.mpicbg.scf:MinCostZSurface_:jar:1.1.6-beta-1-SNAPSHOT in saalfeld-lab-maven-repo (https://saalfeldlab.github.io/maven) -> [Help 1]
```

**Comment by trautmane** [comment]
Hi @tischi, 

At @axtimwalde 's request I released the missing MinCostZSurface_ dependency [here](https://github.com/saalfeldlab/maven#surface-fit-releases) and updated the hot-knife pom in [this commit](https://github.com/saalfeldlab/hot-knife/commit/dc496f0b937dbf98e7ba5bce9f3064833a35783d).  If you pull the latest stuff from the master branch and rebuild, it should compile now.  Let me know here how it goes for you.

Best,
Eric
